services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
#  activemq:
#    image: 'apache/activemq-artemis:latest'
#    ports:
#      - '61616'
#      - "8161:8161"
