spring:
  application.name: TacoJmsDemo

  sql:
    init:
      mode: always

  docker:
    compose:
      lifecycle-management: start_only
  #jms:
  #  template:
  #    session:
  #      transacted: true

  #jms:
  #  listener:
  #    session-transacted: true


tibco:
  ems:
    url: tcp://emsutv1.lmv.lm.se:7222,tcp://emsutv2.lmv.lm.se:7222
    username: ak000020
    password: ak000020