spring:
  application.name: TacoJmsDemo

  sql:
    init:
      mode: always

  docker:
    compose:
      lifecycle-management: start_only
  #jms:
  #  template:
  #    session:
  #      transacted: true

  #jms:
  #  listener:
  #    session-transacted: true